server:
  port: 9000

spring:
  application:
    # 服务名称
    name: cloud-gateway
  cloud:
    nacos:
      # nacos注册中心
      discovery:
        # 服务ip:port
        server-addr: 119.45.5.204:8848
    # 路由网关配置
    gateway:
      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true
      routes:
        # 认证服务
        - id: id-auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
            - Method=GET,POST,PUT,DELETE
        # 用户服务
        - id: id-user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
            - Method=GET,POST,PUT,DELETE

management:
  endpoints:
    web:
      exposure:
        include: '*'
