server:
  port: 9003

spring:
  application:
    # 服务名称
    name: cloud-consumer-feign
  cloud:
    nacos:
      # nacos注册中心
      discovery:
        # 服务ip:port
        server-addr: 119.45.5.204:8848
    openfeign:
      httpclient:
        hc5:
          enabled: true
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: '*'
