server:
  port: 9002
spring:
  application:
    name: cloud-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 119.45.5.204:8848
management:
  endpoints:
    web:
      exposure:
        exclude: "*"
service-url:
  nacos-provider-service: http://cloud-provider
